services:
  app:
    build: .
    ports:
      - "8001:8001"
    volumes:  # sync db because --watch does not sync it
      - ./src/db.sqlite3:/app/src/db.sqlite3
    command: >
          sh -c "python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8001"
    
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            
        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: ["celery", "-A", "src.event_management.celery.application", "worker", "--loglevel=info"]
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
      