services:
  app:
    build: .
    ports:
      - "8001:8001"
    volumes:  # sync db because --watch does not sync it
      - ./src/db.sqlite3:/app/src/db.sqlite3
    
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            
        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
